# -*- coding: utf-8 -*-
"""Atividades Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4v06ecx3Ea-11oFQZu0AKNaT8D0I3Qi

Mensagem "Olá Mundo"
"""

print('Olá Mundo')

"""Soma de dois números"""

print('Escreva dois números para serem somados')
soma = int(input())
num = int(input())
soma = soma + num
print( 'Essa é a soma desses dois números', soma)

"""Escreve masculino caso digite M  e feminino caso digite F"""

print('Digite "M" caso o seu sexo seja masculino, e "F" caso seja Feminino')
sexo = str(input())
if sexo == 'M':
  print(sexo, '-Masculino')
elif sexo == 'F':
  print(sexo, '-Feminino')
else:
  print('Sexo invalido')



"""Calcular as notas de um aluno e mostrar a média, aprovado, reprovado e aprovado com distinção"""

media = 0
print('Escreva a sua nota da prova 1')
nota1 = int(input())
print('Escreva a nota 2')
nota2 = int(input())
media = nota1 + nota2
media = media / 2
print('\nEssa é a média dessas duas notas', media)
if media ==10:
  print('\nParabéns! aprovado com distinção!')
elif media >=7:
  print('\nAprovado')
else:
  print('\nReprovado')

"""Tabuada"""

print('Digite um número para fazer a tabuada')
num = int(input())
for c in range (0,11):
  print(num, 'X', c, '=', num*c)

"""Mostra todos os números impares até o número escolhido"""

print('Escreva um número')
num = int(input())
print('\n')
for c in range(1, num, 2):
  print(c)